<a href="https://colab.research.google.com/github/Hannah1123/Pytorch_note/blob/main/nn_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:

x = torch.randn(128, 20)  # 输入的维度是（128，20）
m = torch.nn.Linear(20, 30)  # 20,30是指维度
output = m(x)
print('m.weight.shape:\n ', m.weight.shape)
print('m.bias.shape:\n', m.bias.shape)
print('output.shape:\n', output.shape)

# ans = torch.mm(input,torch.t(m.weight))+m.bias 等价于下面的
ans = torch.mm(x, m.weight.t()) + m.bias   
print('ans.shape:\n', ans.shape)

print(torch.equal(ans, output))

m.weight.shape:
  torch.Size([30, 20])
m.bias.shape:
 torch.Size([30])
output.shape:
 torch.Size([128, 30])
ans.shape:
 torch.Size([128, 30])
True


In [ ]:
a=torch.randn(2,3)
b=torch.randn(3,2)
print(torch.mm(a,b))
print(torch.matmul(a,b))

tensor([[ 1.7115,  0.4339],
        [ 1.4410, -0.0167]])
tensor([[ 1.7115,  0.4339],
        [ 1.4410, -0.0167]])


In [ ]:
print(a)

tensor([[-0.4930, -0.3423,  0.9058],
        [-0.6561,  1.0766, -0.2152]])
